# Generated by Django 4.2.6 on 2023-10-27 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_name_product_brand_name_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspec',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='spec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.productspec'),
        ),
    ]
