# Generated by Django 4.2.6 on 2023-10-27 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_product_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspec',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='spec',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productspec'),
        ),
    ]
