# Generated by Django 4.2.6 on 2023-10-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_product_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='spec',
        ),
        migrations.AddField(
            model_name='productspec',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
