# Generated by Django 4.2.6 on 2023-10-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_stock_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspec',
            old_name='processor',
            new_name='cpu',
        ),
    ]
