# Generated by Django 4.2.6 on 2023-10-27 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_productspec_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productspec', to='home.product'),
        ),
    ]
