# Generated by Django 4.2.6 on 2023-10-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_productspec_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspec',
            name='display_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='graphics_card_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='memory_detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productspec',
            name='storage_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
