# Generated by Django 4.2.6 on 2023-10-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_productspec_display_detail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSpec',
            new_name='LaptopSpec',
        ),
    ]
