# Generated by Django 4.2.6 on 2023-10-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_productspec_laptopspec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopspec',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptopspec', to='home.product'),
        ),
    ]
