# Generated by Django 4.2.6 on 2023-10-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_brand_category_product_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_category', to='home.brand_category'),
        ),
    ]
