# Generated by Django 4.2.6 on 2023-10-31 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_product_brand_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadphoneSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_size', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency_response', models.CharField(blank=True, max_length=100, null=True)),
                ('impedance', models.CharField(blank=True, max_length=100, null=True)),
                ('noise_cancellation', models.CharField(blank=True, max_length=100, null=True)),
                ('connector_type', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_life', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_features', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headphonespec', to='home.product')),
            ],
        ),
    ]
