# Generated by Django 4.2.6 on 2023-11-01 14:26

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_image',
            field=models.FileField(blank=True, upload_to=home.models.product_directory_path, validators=[home.models.validate_file_extension]),
        ),
    ]
