# Generated by Django 4.2.6 on 2023-11-01 14:30

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_product_related_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=home.models.product_related_images_directory_path, validators=[home.models.validate_file_extension])),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='related_image',
        ),
    ]
