# Generated by Django 4.2.6 on 2023-11-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_productrelatedimage_remove_product_related_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrelatedimage',
            name='product',
            field=models.ManyToManyField(related_name='related_images', to='home.product'),
        ),
    ]
