# Generated by Django 4.2.6 on 2023-11-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_productrelatedimage_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRelatedImage',
        ),
    ]
