# Generated by Django 4.2.6 on 2023-11-01 14:55

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_product_image_2_product_image_3_product_image_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to=home.models.product_directory_path, validators=[home.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to=home.models.product_directory_path, validators=[home.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.FileField(blank=True, null=True, upload_to=home.models.product_directory_path, validators=[home.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_5',
            field=models.FileField(blank=True, null=True, upload_to=home.models.product_directory_path, validators=[home.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_6',
            field=models.FileField(blank=True, null=True, upload_to=home.models.product_directory_path, validators=[home.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=home.models.product_directory_path, validators=[home.models.validate_file_extension]),
        ),
    ]
