# Generated by Django 4.2.6 on 2023-11-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_product_image_2_alter_product_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='yt_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
