# Generated by Django 4.2.6 on 2023-11-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_product_yt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='yt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
