# Generated by Django 4.2.6 on 2023-11-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_product_yt_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='yt_url',
        ),
    ]
