# Generated by Django 4.2.6 on 2023-11-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_product_yt_url_product_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
