# Generated by Django 4.2.6 on 2023-11-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_product_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
