# Generated by Django 4.2.6 on 2023-11-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_product_warranty_product_warranty_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warranty_duration',
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
