# Generated by Django 4.2.6 on 2023-11-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_product_warranty_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopspec',
            name='battery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptopspec',
            name='camera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptopspec',
            name='port',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptopspec',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
