# Generated by Django 4.2.6 on 2023-11-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_laptopspec_battery_laptopspec_camera_laptopspec_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopspec',
            name='wireless_connectivity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
