# Generated by Django 4.2.6 on 2023-11-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_laptopspec_wireless_connectivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptopspec',
            old_name='camera',
            new_name='webcam',
        ),
    ]
