# Generated by Django 4.2.6 on 2023-11-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_rename_camera_laptopspec_webcam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopspec',
            name='port',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
