# Generated by Django 4.2.6 on 2023-11-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_products',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.stock'),
        ),
    ]
