# Generated by Django 4.2.6 on 2023-11-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_brand_category_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
