# Generated by Django 4.2.6 on 2023-11-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_order_cartitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
