# Generated by Django 4.2.7 on 2024-01-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_orderhistory_orderhistoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
