# Generated by Django 4.2.7 on 2024-01-10 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_orderhistory_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
